### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by megadr01d** [rcarmo/rss2imap#20]
I get this traceback although the feeds arrive fine at my inbox... any ideas?

```
Traceback (most recent call last):
  File "rss2email.py", line 976, in <module>
    else: run()
  File "rss2email.py", line 832, in run
    res, data = mailserver.fetch(i, "(UID)")
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 459, in fetch
    typ, dat = self._simple_command(name, message_set, message_parts)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 1091, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 921, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: FETCH command error: BAD ['Error in IMAP command FETCH: Invalid messageset (0.000 + 0.000 secs).']
```

**Comment by rcarmo** [comment]
It looks like something is moving the messages. FETCH retrieves a message and expects it to be there, but that UID is gone. 

I suggest you check for the UIDs being handled, this might even be something specific to your IMAP server. Adding a few logging statements should help.

**Comment by megadr01d** [comment]
I've been using @turbodog's default rss2email and have Sieve filters in place, to deliver feeds to specific folders.
Since rss2imap already provides the option, when importing an `opml` file with `USE_OPML_TITLE_AS_FOLDER = 1`, I forgot to disable the server filters.
It might be it, let me try this for a couple more days (couldn't reproduce it today) and I'll close this issue, if fixed.

**Comment by megadr01d** [comment]
It's probably the service I use, today I started getting `abort: socket error: TLS/SSL connection has been closed (EOF) (_ssl.c:1829)` errors after sending so many feeds, so they must be capping, not only SMTP, but also IMAP transfers.
Closing.

```
=== rss2email encountered a problem with this feed ===
=== See the rss2email FAQ at http://www.allthingsrss.com/rss2email/ for assistance ===
=== If this occurs repeatedly, send this to lindsey@allthingsrss.com ===
E: could not parse https://www.comicsrss.com/rss/zits.rss
Traceback (most recent call last):
  File "/Users/soulitude/repo/rss2imap/rss2email.py", line 783, in run
    mailserver = send(fromhdr, tohdr, subjecthdr, content, contenttype, when, extraheaders, mailserver, f.folder)
  File "/Users/soulitude/repo/rss2imap/rss2email.py", line 155, in send
    if mailserver.select(folder)[0] == 'NO':
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 665, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 1091, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 875, in _command
    raise self.abort('socket error: %s' % val)
abort: socket error: TLS/SSL connection has been closed (EOF) (_ssl.c:1829)
rss2email 2.72-rcarmo
feedparser 5.1.3
html2text 3.200.3
Python 2.7.17 (default, Dec 30 2019, 13:40:03) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
=== END HERE ===
```

**Comment by megadr01d** [comment]
Close.

**Comment by megadr01d** [comment]
It's probably the service I use, today I started getting `abort: socket error: TLS/SSL connection has been closed (EOF) (_ssl.c:1829)` errors after sending so many feeds, so they must be capping, not only SMTP, but also IMAP transfers.
Closing.

```
=== rss2email encountered a problem with this feed ===
=== See the rss2email FAQ at http://www.allthingsrss.com/rss2email/ for assistance ===
=== If this occurs repeatedly, send this to lindsey@allthingsrss.com ===
E: could not parse https://www.comicsrss.com/rss/zits.rss
Traceback (most recent call last):
  File "/Users/soulitude/repo/rss2imap/rss2email.py", line 783, in run
    mailserver = send(fromhdr, tohdr, subjecthdr, content, contenttype, when, extraheaders, mailserver, f.folder)
  File "/Users/soulitude/repo/rss2imap/rss2email.py", line 155, in send
    if mailserver.select(folder)[0] == 'NO':
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 665, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 1091, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 875, in _command
    raise self.abort('socket error: %s' % val)
abort: socket error: TLS/SSL connection has been closed (EOF) (_ssl.c:1829)
rss2email 2.72-rcarmo
feedparser 5.1.3
html2text 3.200.3
Python 2.7.17 (default, Dec 30 2019, 13:40:03) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
=== END HERE ===
```

**Comment by megadr01d** [comment]
@rcarmo, MSGitHub sucks. Can you please close this issue? The "Close" button does nothing on my *not supported browser* Safari 11.1.2 (like we're talking about Netscape Navigator or something). Talk about planned obsolescence.
