### ISSUE TITLE
OPML export malformed

### ISSUE THREAD

**Issue by megadr01d** [rcarmo/rss2imap#21]
```
<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.0">
<head>
<title>rss2email OPML export</title>
</head>
<body>
Traceback (most recent call last):
  File "rss2email.py", line 1014, in <module>
    elif action == "opmlexport": opmlexport()
  File "rss2email.py", line 871, in opmlexport
    exportableFeeds[f.folder].append(f)
AttributeError: 'dict' object has no attribute 'append'
```

The only time it renders correctly, is when I don't have any feeds added.

**Comment by megadr01d** [comment]
I forgot to add that I have custom folders set when I imported them with `opmlimport` and I have some outlines commented out.

Sample of my `opml` feed list:

```
<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.0">
    <head>
        <title>Feed Subscription List</title>
    </head>
    <body>
        <outline title="News">
            <outline xmlUrl="http://ftr.fivefilters.org/makefulltextfeed.php?url=https://mennohenselmans.com/feed/"/>
            ...
        </outline>
        <outline title="Software">
            <outline xmlUrl="https://www.sublimetext.com/blog/feed"/>
            ...
        </outline>
        <outline title="Comics">
            <outline xmlUrl="https://www.bugmartini.com/feed/"/>
            <!-- <outline xmlUrl="http://www.stbeals.com/success?format=RSS"/> -->
            ...
        </outline>
    </body>
</opml>
```

**Comment by megadr01d** [comment]
And I remember that I omitted the `type="rss"` and `text="<feed-title>"` from my list, for easier maintenance. However, if it was imported correctly, it should also export correctly.
